apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-demo
  namespace: ns-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-demo
  template:
    metadata:
      labels:
        app: python-demo
    spec:
      containers:
        - name: python-demo
          image: satson88/python-demo:{{theversion}}