apiVersion: v1
kind: Service
metadata:
  name: svc-python-demo
  namespace: ns-app
spec:
  selector:
    app: python-demo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
